title = "Streaming thoughts"
languageCode = "en-gb"
MetaDataFormat = "toml"
baseurl = "https://jimmidyson.github.io/"
canonifyurls = true

[author]
  name = "Jimmi Dyson"
  image = "http://www.gravatar.com/avatar/c8ab87dec9a30fdb3b8c7c9d0d6f92a9.png"

[author.social]
  twitter = "https://twitter.com/jimmidyson"
  github = "https://github.com/jimmidyson"

[permalinks]
  # Change the permalink format for the 'post' content type.
  post = "/:title/"

[params]

  # Default page metadata, used when the specific page doesn't set its own.
  defaultDescription = "Current projects & general musings"
  defaultKeywords = "jimmi dyson,home,website,blog"

  disqusShortname = "jimmidyson"

  # Tagline to display under the author name in the sidebar, keep it short.
  tagline = "Current projects & general musings"

  # Metadata used to drive integrations.
  googleAnalytics = "UA-32984711-1"

  #cover = "/img/cover.jpg"

